name: Deploy to EC2 via HTTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: |
          git clone https://${{ secrets.BAKGOM_TOKEN }}@github.com/bakgom123/docker_kakao_community.git

      - name: Deploy to EC2 via HTTPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> << 'EOF'
          cd /home/ubuntu/your-repo
          docker-compose down
          docker-compose up -d --build
          EOF